# HISTORY FILE FOR ZSH
HISTFILE=~/.zsh_history

# PURE
fpath+=($HOME/.zsh/pure)

autoload -U promptinit; promptinit
prompt pure

# ZIG-SHELL-COMPLETIONS
fpath+=($HOME/.zsh/zig-shell-completions)

# POETRY
fpath+=~/.zfunc

# NVM
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# ASDF
. "$HOME/.asdf/asdf.sh"
fpath=(${ASDF_DIR}/completions $fpath)

# FIX ARROW KEYS
bindkey "\e[1;5C" forward-word
bindkey "\e[1;5D" backward-word

export PATH="$PATH:/opt/nvim-linux64/bin:/home/mckatoo/.local/bin:/home/mckatoo/.zig"

autoload -U compinit
compinit -i
autoload -Uz compinit && compinit

# ZSH-SYNTAX-HIGHLIGHTING
source /usr/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# ZSH-AUTOSUGGESTIONS
source /usr/share/zsh-autosuggestions/zsh-autosuggestions.zsh


# BEGIN - GENERATED BY ALIASES CLI
reload_aliases() {
            source ~/.aliases
        }
source $HOME/.aliases

# BUN COMPLETIONS
[ -s "/home/mckatoo/.bun/_bun" ] && source "/home/mckatoo/.bun/_bun"

# NPM COMPLETION
source $HOME/.zsh/npm/npm-completion.zsh

# DENO PATH
export DENO_INSTALL="/home/mckatoo/.deno"
export PATH="$DENO_INSTALL/bin:$PATH"

# DENO COMPLETION
fpath=(~/.zsh $fpath)
autoload -Uz compinit
compinit -u

# GO SETTINGS
export GOPATH=$HOME/.go
export PATH=$PATH:/usr/local/go/bin:$GOPATH/bin

# GITIGNORE CLI
function gi() {
  curl -sLw "\n" https://www.toptal.com/developers/gitignore/api/$@ ;
}

# >>> xmake >>>
test -f "/home/mckatoo/.xmake/profile" && source "/home/mckatoo/.xmake/profile"
# <<< xmake <<<

# HISTORY CONFIG
test -f "$HOME/history.zsh" && source "$HOME/history.zsh"
